#if !defined(AFX_MMHITIMERX_H__7D51AA78_1A3D_4BC0_BD18_688A48FDF223__INCLUDED_)
#define AFX_MMHITIMERX_H__7D51AA78_1A3D_4BC0_BD18_688A48FDF223__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMMHiTimerX wrapper class

class CMMHiTimerX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMMHiTimerX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xb6f5c923, 0xd61b, 0x11d1, { 0x88, 0x18, 0xc1, 0x99, 0x19, 0x8e, 0x97, 0x2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetCallBackMode();
	void SetCallBackMode(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	long GetInterval();
	void SetInterval(long nNewValue);
	long GetPriority();
	void SetPriority(long nNewValue);
	BOOL GetSynchronize();
	void SetSynchronize(BOOL bNewValue);
	BOOL GetWaitForTerminate();
	void SetWaitForTerminate(BOOL bNewValue);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MMHITIMERX_H__7D51AA78_1A3D_4BC0_BD18_688A48FDF223__INCLUDED_)
