// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVSFlexDataSource wrapper class

class CVSFlexDataSource : public COleDispatchDriver
{
public:
	CVSFlexDataSource() {}		// Calls COleDispatchDriver default constructor
	CVSFlexDataSource(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVSFlexDataSource(const CVSFlexDataSource& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetFieldCount();
	long GetRecordCount();
	CString GetFieldName(long Field);
	CString GetData(long Field, long Record);
	void SetData(long Field, long Record, LPCTSTR newData);
};
