// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMMBevelX wrapper class

class CMMBevelX : public COleDispatchDriver
{
public:
	CMMBevelX() {}		// Calls COleDispatchDriver default constructor
	CMMBevelX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMMBevelX(const CMMBevelX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetBevelInner();
	void SetBevelInner(long nNewValue);
	long GetBevelInnerWidth();
	void SetBevelInnerWidth(long nNewValue);
	long GetBevelOuter();
	void SetBevelOuter(long nNewValue);
	long GetBevelOuterWidth();
	void SetBevelOuterWidth(long nNewValue);
	unsigned long GetBorderColor();
	void SetBorderColor(unsigned long newValue);
	long GetBorderSpace();
	void SetBorderSpace(long nNewValue);
	unsigned long GetBorderSpaceColor();
	void SetBorderSpaceColor(unsigned long newValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	long GetBorderWidth();
	void SetBorderWidth(long nNewValue);
	unsigned long GetInnerLightColor();
	void SetInnerLightColor(unsigned long newValue);
	unsigned long GetInnerShadowColor();
	void SetInnerShadowColor(unsigned long newValue);
	unsigned long GetOuterLightColor();
	void SetOuterLightColor(unsigned long newValue);
	unsigned long GetOuterShadowColor();
	void SetOuterShadowColor(unsigned long newValue);
};
