#if !defined(AFX_MMLEDLABELX_H__A1B240C3_7AE4_4AFC_A29C_986EF1E787AC__INCLUDED_)
#define AFX_MMLEDLABELX_H__A1B240C3_7AE4_4AFC_A29C_986EF1E787AC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMMBevelX;

/////////////////////////////////////////////////////////////////////////////
// CMMLEDLABELX wrapper class

class CMMLEDLABELX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMMLEDLABELX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd4f4dec3, 0xd6bc, 0x11d1, { 0x88, 0x18, 0xc1, 0x99, 0x19, 0x8e, 0x97, 0x2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	BOOL GetAutoSize();
	void SetAutoSize(BOOL bNewValue);
	long GetAlignment();
	void SetAlignment(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	long GetFontSize();
	void SetFontSize(long nNewValue);
	BOOL GetDrawInactive();
	void SetDrawInactive(BOOL bNewValue);
	unsigned long GetInactiveColor();
	void SetInactiveColor(unsigned long newValue);
	unsigned long GetLEDColor();
	void SetLEDColor(unsigned long newValue);
	long GetNumChars();
	void SetNumChars(long nNewValue);
	long GetLEDSpace();
	void SetLEDSpace(long nNewValue);
	long GetScrollSpeed();
	void SetScrollSpeed(long nNewValue);
	long GetStartStep();
	void SetStartStep(long nNewValue);
	long GetCurrentStep();
	void SetCurrentStep(long nNewValue);
	BOOL GetAutoScroll();
	void SetAutoScroll(BOOL bNewValue);
	CMMBevelX GetBevel();
	long GetCursor();
	void SetCursor(long nNewValue);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MMLEDLABELX_H__A1B240C3_7AE4_4AFC_A29C_986EF1E787AC__INCLUDED_)
