#if !defined(AFX_MMWAVEINX_H__090C9347_7162_441D_8DAB_D045FCEB3A32__INCLUDED_)
#define AFX_MMWAVEINX_H__090C9347_7162_441D_8DAB_D045FCEB3A32__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMMDspComponentX;

/////////////////////////////////////////////////////////////////////////////
// CMMWaveInX wrapper class

class CMMWaveInX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMMWaveInX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xf66a4fc3, 0xdc4e, 0x11d1, { 0x88, 0x18, 0xc1, 0x99, 0x19, 0x8e, 0x97, 0x2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetNumdevs();
	long GetDriverVersion();
	long GetBytesRecorded();
	long GetPosition();
	long GetHandle();
	long GetBufferSize();
	void SetBufferSize(long nNewValue);
	long GetCallBackMode();
	void SetCallBackMode(long nNewValue);
	long GetDeviceID();
	void SetDeviceID(long nNewValue);
	long GetNumBuffers();
	void SetNumBuffers(long nNewValue);
	long GetMode();
	void SetMode(long nNewValue);
	long GetBitLength();
	void SetBitLength(long nNewValue);
	long GetSampleRate();
	void SetSampleRate(long nNewValue);
	CString GetProductName();
	void SetProductName(LPCTSTR lpszNewValue);
	long GetTimeFormat();
	void SetTimeFormat(long nNewValue);
	long GetMaxRecordTime();
	void SetMaxRecordTime(long nNewValue);
	void Open();
	void Close();
	void Start();
	void Pause();
	void Restart();
	void Stop();
	long GetState();
	CString GetDeviceName(long DeviceID);
	BOOL DeviceFullDuplex(long DeviceID, long pwfx);
	BOOL DeviceReady(long DeviceID);
	long GetPriority();
	void SetPriority(long nNewValue);
	long GetPWaveFormat();
	void SetPWaveFormat(long nNewValue);
	CMMDspComponentX GetOutput();
	void SetOutput(LPDISPATCH newValue);
	CString GetOutputX();
	void SetOutputX(LPCTSTR lpszNewValue);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MMWAVEINX_H__090C9347_7162_441D_8DAB_D045FCEB3A32__INCLUDED_)
