#if !defined(AFX_MMWAVEOUTX_H__67D35A84_8363_4DDD_8194_4CC4B6CC8305__INCLUDED_)
#define AFX_MMWAVEOUTX_H__67D35A84_8363_4DDD_8194_4CC4B6CC8305__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMMDspComponentX;

/////////////////////////////////////////////////////////////////////////////
// CMMWaveOutX wrapper class

class CMMWaveOutX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMMWaveOutX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe247fbc3, 0xdd0d, 0x11d1, { 0x88, 0x18, 0xc1, 0x99, 0x19, 0x8e, 0x97, 0x2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetHandle();
	long GetNumdevs();
	long GetDriverVersion();
	long GetBytesPlayed();
	long GetPosition();
	long GetPositionHigh();
	long GetBufferSize();
	void SetBufferSize(long nNewValue);
	long GetNumBuffers();
	void SetNumBuffers(long nNewValue);
	long GetDeviceID();
	void SetDeviceID(long nNewValue);
	CString GetProductName();
	void SetProductName(LPCTSTR lpszNewValue);
	long GetTimeFormat();
	void SetTimeFormat(long nNewValue);
	long GetCallBackMode();
	void SetCallBackMode(long nNewValue);
	BOOL GetLooping();
	void SetLooping(BOOL bNewValue);
	long GetLoopCount();
	void SetLoopCount(long nNewValue);
	BOOL GetShowHourGlass();
	void SetShowHourGlass(BOOL bNewValue);
	void Open();
	void Close();
	void Reset();
	void Start();
	void Pause();
	void Restart();
	void Stop();
	long GetState();
	CString GetDeviceName(long DeviceID);
	BOOL DeviceFullDuplex(long DeviceID, long pwfx);
	BOOL DeviceReady(long DeviceID);
	long GetPriority();
	void SetPriority(long nNewValue);
	long GetPWaveFormat();
	void SetPWaveFormat(long nNewValue);
	CMMDspComponentX GetInput();
	void SetInput(LPDISPATCH newValue);
	CString GetInputX();
	void SetInputX(LPCTSTR lpszNewValue);
	CMMDspComponentX GetOutput();
	void SetOutput(LPDISPATCH newValue);
	CString GetOutputX();
	void SetOutputX(LPCTSTR lpszNewValue);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MMWAVEOUTX_H__67D35A84_8363_4DDD_8194_4CC4B6CC8305__INCLUDED_)
