// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CVSFlexNode wrapper class

class CVSFlexNode : public COleDispatchDriver
{
public:
	CVSFlexNode() {}		// Calls COleDispatchDriver default constructor
	CVSFlexNode(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVSFlexNode(const CVSFlexNode& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	CString GetKey();
	void SetKey(LPCTSTR lpszNewValue);
	CPicture GetImage();
	void SetImage(LPDISPATCH newValue);
	void SetRefImage(LPDISPATCH newValue);
	BOOL GetExpanded();
	void SetExpanded(BOOL bNewValue);
	short GetLevel();
	long GetChildren();
	long GetRow();
	void SetRow(long nNewValue);
	BOOL Move(long MoveTo, const VARIANT& TargetNode);
	void Sort(long How);
	void EnsureVisible();
	void Select();
	CVSFlexNode GetNode(long Which);
	CVSFlexNode AddNode(long AddWhere, LPCTSTR Item, const VARIANT& Key, const VARIANT& Image);
	void RemoveNode();
};
