// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMMDspComponentX wrapper class

class CMMDspComponentX : public COleDispatchDriver
{
public:
	CMMDspComponentX() {}		// Calls COleDispatchDriver default constructor
	CMMDspComponentX(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMMDspComponentX(const CMMDspComponentX& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIsOpen();
	CMMDspComponentX GetInput();
	void SetInput(LPDISPATCH newValue);
	CString GetInputX();
	void SetInputX(LPCTSTR lpszNewValue);
	CMMDspComponentX GetOutput();
	void SetOutput(LPDISPATCH newValue);
	CString GetOutputX();
	void SetOutputX(LPCTSTR lpszNewValue);
	CMMDspComponentX GetDSPInterface();
	BOOL CanConnectInput(LPDISPATCH Int);
	BOOL CanConnectOutput(LPDISPATCH Int);
};
