#if !defined(AFX_MMLEDPANELX_H__0A04EB4A_7E18_4676_8B46_768AA59D0C21__INCLUDED_)
#define AFX_MMLEDPANELX_H__0A04EB4A_7E18_4676_8B46_768AA59D0C21__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMMBevelX;

/////////////////////////////////////////////////////////////////////////////
// CMMLEDPanelX wrapper class

class CMMLEDPanelX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMMLEDPanelX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8cbbb803, 0xd654, 0x11d1, { 0x88, 0x18, 0xc1, 0x99, 0x19, 0x8e, 0x97, 0x2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	BOOL GetDrawInactive();
	void SetDrawInactive(BOOL bNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	unsigned long GetLEDColor();
	void SetLEDColor(unsigned long newValue);
	unsigned long GetInactiveColor();
	void SetInactiveColor(unsigned long newValue);
	long GetNumDigits();
	void SetNumDigits(long nNewValue);
	long GetDigitSize();
	void SetDigitSize(long nNewValue);
	long GetLEDSpace();
	void SetLEDSpace(long nNewValue);
	long GetMaxValue();
	void SetMaxValue(long nNewValue);
	long GetMinValue();
	void SetMinValue(long nNewValue);
	BOOL GetZeroBlank();
	void SetZeroBlank(BOOL bNewValue);
	long GetValue();
	void SetValue(long nNewValue);
	CMMBevelX GetBevel();
	long GetCursor();
	void SetCursor(long nNewValue);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MMLEDPANELX_H__0A04EB4A_7E18_4676_8B46_768AA59D0C21__INCLUDED_)
